/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionbasedatos;

import entities.Libros;
import entities.Editoriales;
import java.awt.Frame;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;

/**
 *
 * @author Raul
 */
public class DatosLibros extends javax.swing.JPanel {

    /**
     * Creates new form DatosLibros
     */
    Libros libro;
    Editoriales editorial;

    public DatosLibros() {
        initComponents();
    }

    public void setLibro(Libros libro) {
        this.libro = libro;
    }

    public void showDates() {
        jTextFieldTitutlo.setText(libro.getTitulo());
        jTextFieldAutor.setText(libro.getAutores());
        jTextFieldPrecio.setText(String.valueOf(libro.getPvpsiniva()));
        if (libro.getIdEditorial() != null) {
            jTextFieldEditorial.setText(libro.getIdEditorial().getNombre());
        } else {
            jTextFieldEditorial.setText("");
        }
        if (libro.getFechaEdicion() != null) {
            jDateChooser1.setDate(libro.getFechaEdicion());
        } else {
            jDateChooser1.setDate(null);
        }
        jTextFieldStockActual.setText(String.valueOf(libro.getStockactual()));
    }

    public void activarCampos(boolean activar) {
        jTextFieldTitutlo.setEditable(activar);
        jTextFieldAutor.setEditable(activar);
        jTextFieldPrecio.setEditable(activar);
        jTextFieldEditorial.setEditable(activar);
        jDateChooser1.setEnabled(activar);
        jTextFieldStockActual.setEditable(activar);
    }

    public void limpiarCampos() {
        jTextFieldTitutlo.setText("");
        jTextFieldAutor.setText("");
        jTextFieldPrecio.setText("");
        jTextFieldEditorial.setText("");
        jTextFieldStockActual.setText("");
        jDateChooser1.setDate(null);
    }

    public boolean isCamposVacios() {
        return jTextFieldTitutlo.getText().isEmpty()
                || jTextFieldAutor.getText().isEmpty()
                || jTextFieldPrecio.getText().isEmpty()
                || jTextFieldStockActual.getText().isEmpty();
    }

    public Libros setDatos() {
        Libros libronuevo = new Libros();
        libronuevo.setTitulo(jTextFieldTitutlo.getText());
        libronuevo.setAutores(jTextFieldAutor.getText());
        libronuevo.setPvpsiniva(BigDecimal.valueOf(Double.valueOf(jTextFieldPrecio.getText())));
        //editorial.setNombre(jTextField4.getText());
        //libronuevo.setIdEditorial(editorial);
        libronuevo.setFechaEdicion(jDateChooser1.getDate());
        libronuevo.setStockactual(Integer.valueOf(jTextFieldStockActual.getText()));
        return libronuevo;
    }
    public void setfocus(){
        jTextFieldTitutlo.requestFocus();
    }
    
    public void activarBEditoriales(boolean activar){
        b_Editoriales.setEnabled(activar);
    }

    public void showEditorial() {
        if(editorial != null) {
            jTextFieldEditorial.setText(editorial.getIdEditorial() + " - " + editorial.getNombre());
        }
    }

    public Editoriales getEditorial() {
        return editorial;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldTitutlo = new javax.swing.JTextField();
        jTextFieldPrecio = new javax.swing.JTextField();
        jTextFieldAutor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldEditorial = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldStockActual = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        b_Editoriales = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setText("Título*");

        jTextFieldTitutlo.setEditable(false);

        jTextFieldPrecio.setEditable(false);

        jTextFieldAutor.setEditable(false);

        jLabel2.setText("Autor*");

        jLabel3.setText("Precio*");

        jTextFieldEditorial.setEditable(false);

        jLabel4.setText("Editorial");

        jLabel5.setText("Fecha Edición");

        jTextFieldStockActual.setEditable(false);

        jLabel6.setText("Stock Actual*");

        b_Editoriales.setText("Editoriales...");
        b_Editoriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_EditorialesActionPerformed(evt);
            }
        });

        jLabel7.setText("(*)Campos obligatorios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldStockActual)
                            .addComponent(jTextFieldTitutlo)
                            .addComponent(jTextFieldPrecio)
                            .addComponent(jTextFieldAutor)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTextFieldEditorial, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                .addGap(8, 8, 8)
                                .addComponent(b_Editoriales))
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldTitutlo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(b_Editoriales))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldStockActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void b_EditorialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_EditorialesActionPerformed
        Frame frameParent = Frame.getFrames()[0];
        DialogListaEditoriales dialogListaEditoriales = new DialogListaEditoriales(frameParent, true);
        dialogListaEditoriales.setVisible(true);
        
        //Obtener la editorial que se ha seleccionado en la ventana de diálogo
        editorial = dialogListaEditoriales.getEditorialSelec();
        showEditorial();
    }//GEN-LAST:event_b_EditorialesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_Editoriales;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextFieldAutor;
    private javax.swing.JTextField jTextFieldEditorial;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldStockActual;
    private javax.swing.JTextField jTextFieldTitutlo;
    // End of variables declaration//GEN-END:variables
}
